usuario = pr3
contraseña = 123456

rutaEmpleados=src/main/resources/persistencia/empleados.txt
rutaDepartamentos=src/main/resources/persistencia/departamentos.txt
rutaProyectos=src/main/resources/persistencia/proyectos.txt
rutaXml = src/main/resources/persistencia/modelRecursoHumano.xml
rutaBinario = src/main/resources/persistencia/model.dat